### ISSUE TITLE
Error building when using plugin

### ISSUE THREAD

**Issue by Lecramed** [Telerik-Verified-Plugins/Badge#1]
Hello, 
I get an error when building with this plugin.
also mentioned in: https://github.com/katzer/cordova-plugin-badge/issues/70

Can you please update the Telerik Verified Plugin?
Or advise how to use the functionality provided by this plugin.

Greetings
Marcel

Error message:
Warning: Failed to install 'de.appplant.cordova.plugin.badge':CordovaError: Failed to fetch plugin de.appplant.cordova.common.registerusernotificationsettings via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/de.appplant.cordova.common.registerusernotificationsettings
    at /Users/builder/BpcTooling/Cordova3/pm-5.0+/node_modules/cordova-lib/cordova-lib/src/plugman/fetch.js:170:33
    at _rejected (/Users/builder/BpcTooling/Cordova3/pm-5.0+/node_modules/q/q.js:797:24)
    at /Users/builder/BpcTooling/Cordova3/pm-5.0+/node_modules/q/q.js:823:30
    at Promise.when (/Users/builder/BpcTooling/Cordova3/pm-5.0+/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/Users/builder/BpcTooling/Cordova3/pm-5.0+/node_modules/q/q.js:741:41)
    at /Users/builder/BpcTooling/Cordova3/pm-5.0+/node_modules/q/q.js:557:44
    at flush (/Users/builder/BpcTooling/Cordova3/pm-5.0+/node_modules/q/q.js:108:17)
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    Warning: Failed to fetch plugin de.appplant.cordova.common.registerusernotificationsettings via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/de.appplant.cordova.common.registerusernotificationsettings
    Warning: /Users/builder/BpcTooling/Cordova3/node_modules/cordova-build-utils/bin/install-plugins-3.js:190
                            throw Error("exit code: " + code);
                            ^

Error: exit code: 1
    at Error (native)
    at ChildProcess.<anonymous> (/Users/builder/BpcTooling/Cordova3/node_modules/cordova-build-utils/bin/install-plugins-3.js:190:14)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

**Comment by EddyVerbruggen** [comment]
Hi @Lecramed do you still need assistance or did the comment in the upstream repo fix it?

**Comment by Lecramed** [comment]
version 0.72 fixed the issue
Thanks
